version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: restaurant_system_db
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: WSSHLI
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 restaurant_system.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - SECRET_KEY=your-secret-key-here
      - DEBUG=True
      - DATABASE_URL=postgres://restaurant_user:WSSHLI@db:5432/restaurant_system_db
      - REDIS_URL=redis://redis:6379

volumes:
  postgres_data: